import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  tr: {
    "nav.speakers": "Konuklar",
    "nav.schedule": "Program",
    "nav.sponsorship": "Sponsorlar",
    "nav.contact": "İletişim",
    "hero.title1": "SOSYAL MEDYA",
    "hero.title2": "SÖYLEŞİLERİ ’26",
    "hero.date": "15–16 Nisan 2026",
    "hero.location": "M.A. Ersoy Salonu • Beytepe",
    "hero.btn_schedule": "Programı İncele",
    "hero.btn_speakers": "Konuklarla Tanış",
    "exp.tag": "Etkinlik Ruhu",
    "exp.title": "SMS Nedir?",
    "exp.p1": "Sosyal Medya Söyleşileri (SMS), ACM Hacettepe Öğrenci Topluluğu tarafından her yıl geleneksel olarak düzenlenen, Türkiye'nin en dinamik kampüs zirvesidir.",
    "exp.p2": "Sektör profesyonellerini, içerik üreticilerini ve dijital dünyanın vizyonerlerini Hacettepe Üniversitesi'nin enerjisiyle buluşturuyoruz. Sadece bir konferans değil; samimiyetin ve gerçek deneyimlerin paylaşıldığı profesyonel bir sahne atmosferi sunuyoruz.",
    "exp.portraits": "Konuk Portreleri",
    "exp.badge": "Hacettepe • SMS’26",
    "speakers.lineup": "Lineup",
    "speakers.title": "Konuklar",
    "speakers.day1": "GÜN 1 • 15 Nisan",
    "speakers.day2": "GÜN 2 • 16 Nisan",
    "modal.day": "GÜN",
    "modal.about": "Hakkında",
    "modal.links": "Bağlantılar",
    "schedule.title": "PROGRAM",
    "schedule.title_accent": "AKIŞI",
    "schedule.wed": "Çarşamba",
    "schedule.thu": "Perşembe",
    "schedule.day1": "1. GÜN",
    "schedule.day2": "2. GÜN",
    "stats.dashboard": "Analiz Paneli",
    "stats.title": "Rakamlarla SMS Gücü",
    "stats.1.label": "Topluluk Erişimi",
    "stats.1.desc": "Aktif topluluk üyeleri ve takipçiler.",
    "stats.2.label": "Üniversite Kitlesi",
    "stats.2.desc": "Hacettepe Üniversitesi kampüs ekosistemi.",
    "stats.3.label": "Gen Z Hedef Kitle",
    "stats.3.desc": "Dijital yerli ve trend belirleyici kitle.",
    "stats.callout": "Ankara’nın en canlı kampüs etkinliklerinden birinde doğru kitleyle buluşun.",
    "stats.btn": "Bize Katılın",
    "team.title": "ETKİNLİK",
    "team.title_accent": "SORUMLULARI",
    "team.director": "Etkinlik Direktörü",
    "team.coordinator": "Etkinlik Sorumlusu",
    "cta.title": "Şovun bir parçası olun.",
    "cta.sponsor.title": "Sponsor Ol",
    "cta.sponsor.desc": "Markanızı Ankara'nın en dinamik kampüs kitlesiyle buluşturun. SMS'26'nın enerjisini paylaşarak görünürlüğünüzü zirveye taşıyın.",
    "cta.sponsor.btn": "Hemen Başvur",
    "cta.speaker.title": "Konuğumuz Ol",
    "cta.speaker.desc": "Dijital dünyadaki deneyimlerinizi binlerce öğrenciyle paylaşın. Sahne enerjimize ortak olun, hikayenizi birlikte anlatalım.",
    "cta.speaker.btn": "Sahnede Yer Al",
    "contact.title": "İletişim",
    "contact.subtitle": "Sorularınız için bize ulaşın.",
    "contact.desc": "Sponsorluk, katılım veya sadece merhaba demek için bize ulaşın. Ekibimiz en kısa sürede dönüş yapacaktır.",
    "contact.email_label": "E-Posta Adresimiz",
    "contact.form.name": "İsim",
    "contact.form.name_ph": "Adınız",
    "contact.form.email": "Email",
    "contact.form.email_ph": "Emailiniz",
    "contact.form.message": "Mesaj",
    "contact.form.message_ph": "Mesajınızı buraya yazın...",
    "contact.form.category": "Mesaj Kategorisi",
    "contact.category.general": "Genel İletişim",
    "contact.category.guest": "Konuk Ol",
    "contact.category.sponsor": "Sponsor Ol",
    "contact.category.feedback": "Geri Bildirim",
    "contact.category.request": "İstek / Görüş",
    "contact.category.other": "Diğer",
    "contact.form.btn": "Mesaj Gönder",
    "contact.success": "Başarılı!",
    "contact.success_desc": "Mesajınız ACM ekibine ulaştı.",
    "footer.desc": "ACM Hacettepe tarafından düzenlenen SMS, dijital dünyayı kampüs enerjisiyle buluşturan prestijli bir vizyon etkinliğidir.",
    "footer.menu": "Hızlı Menü",
    "footer.follow": "Bizi Takip Edin",
    "footer.channels": "Resmi kanallar",
    "spon.tag": "Partnerlik",
    "spon.title": "Sponsorlar",
    "spon.main": "Ana Sponsor",
    "spon.platinum": "Platin Sponsor",
    "spon.gold": "Altın Sponsor",
    "spon.silver": "Gümüş Sponsor",
    "spon.waiting": "İsim Bekleniyor",
    "spon.logo": "Logo Alanı",
    "spon.partner_name": "Partner İsmi",
    "spon.logo_small": "Logo",
    "speakers.special_guest": "Özel Konuk"
  },
  en: {
    "nav.speakers": "Speakers",
    "nav.schedule": "Schedule",
    "nav.sponsorship": "Sponsorship",
    "nav.contact": "Contact",
    "hero.title1": "SOCIAL MEDIA",
    "hero.title2": "TALKS ’26",
    "hero.date": "April 15–16, 2026",
    "hero.location": "M.A. Ersoy Hall • Beytepe",
    "hero.btn_schedule": "View Schedule",
    "hero.btn_speakers": "Meet Speakers",
    "exp.tag": "Event Spirit",
    "exp.title": "What is SMS?",
    "exp.p1": "Social Media Talks (SMS) is the most dynamic campus summit in Turkey, traditionally organized every year by the ACM Hacettepe Student Community.",
    "exp.p2": "We bring together industry professionals, content creators, and visionaries of the digital world with the energy of Hacettepe University. It's not just a conference; we offer a professional stage atmosphere where sincerity and real experiences are shared.",
    "exp.portraits": "Guest Portraits",
    "exp.badge": "Hacettepe • SMS’26",
    "speakers.lineup": "Lineup",
    "speakers.title": "Speakers",
    "speakers.day1": "DAY 1 • April 15",
    "speakers.day2": "DAY 2 • April 16",
    "modal.day": "DAY",
    "modal.about": "About",
    "modal.links": "Links",
    "schedule.title": "EVENT",
    "schedule.title_accent": "SCHEDULE",
    "schedule.wed": "Wednesday",
    "schedule.thu": "Thursday",
    "schedule.day1": "DAY 1",
    "schedule.day2": "DAY 2",
    "stats.dashboard": "Analytics Dashboard",
    "stats.title": "SMS Power in Numbers",
    "stats.1.label": "Community Reach",
    "stats.1.desc": "Active community members and followers.",
    "stats.2.label": "University Audience",
    "stats.2.desc": "Hacettepe University campus ecosystem.",
    "stats.3.label": "Gen Z Target",
    "stats.3.desc": "Digital native and trendsetter audience.",
    "stats.callout": "Meet the right audience at one of Ankara's most vibrant campus events.",
    "stats.btn": "Join Us",
    "team.title": "EVENT",
    "team.title_accent": "COORDINATORS",
    "team.director": "Event Director",
    "team.coordinator": "Event Coordinator",
    "cta.title": "Be a part of the show.",
    "cta.sponsor.title": "Become a Sponsor",
    "cta.sponsor.desc": "Connect your brand with Ankara's most dynamic campus audience. Share the energy of SMS'26 and peak your visibility.",
    "cta.sponsor.btn": "Apply Now",
    "cta.speaker.title": "Be Our Guest",
    "cta.speaker.desc": "Share your digital experiences with thousands of students. Partner with our stage energy, let's tell your story together.",
    "cta.speaker.btn": "Take the Stage",
    "contact.title": "Contact",
    "contact.subtitle": "Contact us for your questions.",
    "contact.desc": "Contact us for sponsorship, participation, or just to say hello. Our team will get back to you as soon as possible.",
    "contact.email_label": "Our Email Address",
    "contact.form.name": "Name",
    "contact.form.name_ph": "Your Name",
    "contact.form.email": "Email",
    "contact.form.email_ph": "Your Email",
    "contact.form.message": "Message",
    "contact.form.message_ph": "Write your message here...",
    "contact.form.category": "Message Category",
    "contact.category.general": "General Inquiry",
    "contact.category.guest": "Become a Guest",
    "contact.category.sponsor": "Become a Sponsor",
    "contact.category.feedback": "Feedback",
    "contact.category.request": "Request / Opinion",
    "contact.category.other": "Other",
    "contact.form.btn": "Send Message",
    "contact.success": "Success!",
    "contact.success_desc": "Your message has reached the ACM team.",
    "footer.desc": "Organized by ACM Hacettepe, SMS is a prestigious vision event that brings the digital world together with campus energy.",
    "footer.menu": "Quick Menu",
    "footer.follow": "Follow Us",
    "footer.channels": "Official channels",
    "spon.tag": "Partnership",
    "spon.title": "Sponsorship Packages",
    "spon.main": "Main Sponsor",
    "spon.platinum": "Platinum Sponsor",
    "spon.gold": "Gold Sponsor",
    "spon.silver": "Silver Sponsor",
    "spon.waiting": "Name Pending",
    "spon.logo": "Logo Area",
    "spon.partner_name": "Partner Name",
    "spon.logo_small": "Logo",
    "speakers.special_guest": "Special Guest"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('tr');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};